[project]
name = "rewindai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.5"
dependencies = [
    "google-generativeai>=0.8.6",
    "langchain>=1.2.10",
    "langchain-core>=1.2.13",
    "langchain-google-genai>=4.2.0",
    "langgraph>=1.0.8",
    "langgraph-checkpoint-postgres>=3.0.4",
    "psycopg[binary]>=3.3.2",
    "python-dotenv>=1.2.1",
]
